// Command gencommands reads the normalized OpenAPI spec and emits a compact
// operations manifest (cmd/operations.gen.go). The CLI builds a generic,
// spec-driven command tree from that manifest at startup (see cmd/generic.go),
// so the entire API surface is reachable without hand-writing a command per
// endpoint — and a regen tracks any spec change automatically.
//
// Usage: gencommands <input-spec.yaml> <output.go>
package main

import (
	"fmt"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

type op struct {
	Tag     string
	OpID    string
	Summary string
	Method  string
	Path    string
}

// methodRank gives a stable ordering for verbs sharing a path.
var methodRank = map[string]int{"get": 0, "post": 1, "put": 2, "patch": 3, "delete": 4}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gencommands <input.yaml> <output.go>")
		os.Exit(2)
	}
	data, err := os.ReadFile(os.Args[1])
	must(err)

	var root map[string]any
	must(yaml.Unmarshal(data, &root))

	ops := extractOps(root)

	out, err := os.Create(os.Args[2])
	must(err)
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by tools/gencommands. DO NOT EDIT.")
	fmt.Fprintln(out, "package cmd")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// generatedOperations is the full set of API operations, used to build the")
	fmt.Fprintln(out, "// generic spec-driven command tree (see generic.go).")
	fmt.Fprintln(out, "var generatedOperations = []opSpec{")
	for _, o := range ops {
		if o.OpID == "" {
			continue
		}
		fmt.Fprintf(out, "\t{Tag: %q, OpID: %q, Summary: %q, Method: %q, Path: %q},\n",
			o.Tag, o.OpID, firstLine(o.Summary), o.Method, o.Path)
	}
	fmt.Fprintln(out, "}")
}

// extractOps walks the decoded spec's paths and returns one op per
// method+path, sorted deterministically (by path, then by method) so the
// generated file has a stable diff.
func extractOps(root map[string]any) []op {
	paths, _ := root["paths"].(map[string]any)
	var ops []op
	for path, raw := range paths {
		item, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		for method := range methodRank {
			mraw, ok := item[method].(map[string]any)
			if !ok {
				continue
			}
			ops = append(ops, op{
				Tag:     firstTag(mraw),
				OpID:    str(mraw["operationId"]),
				Summary: str(mraw["summary"]),
				Method:  method,
				Path:    path,
			})
		}
	}
	sort.SliceStable(ops, func(i, j int) bool {
		if ops[i].Path != ops[j].Path {
			return ops[i].Path < ops[j].Path
		}
		return methodRank[ops[i].Method] < methodRank[ops[j].Method]
	})
	return ops
}

func firstTag(m map[string]any) string {
	tags, ok := m["tags"].([]any)
	if !ok || len(tags) == 0 {
		return "Other"
	}
	return str(tags[0])
}

func str(v any) string {
	s, _ := v.(string)
	return s
}

// firstLine keeps summaries to a single line for help text.
func firstLine(s string) string {
	for i, r := range s {
		if r == '\n' {
			return s[:i]
		}
	}
	return s
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "gencommands:", err)
		os.Exit(1)
	}
}
